include(":presentation:home")


include(":app")
include(":core:component")
include(":core:constants")
include(":core:utils")
include(":core:testutils")
include(":core:framework")
include(":core:provider")
include(":core:theme")
include(":data:local")
include(":data:remote")
include(":data:model")
include(":data:repository")
include(":domain:entity")
include(":domain:usecase")
include(":presentation:splash")
include(":presentation:welcome")
include(":presentation:products")
include(":presentation:settings")
