/**
 *   @author xavierjimenez
 *   @since 8/3/23
 *   @email xavijimenezmulet@macaqueconsulting.com
 */
object Versions {
  const val compileSdk = 33
  const val targetSdk = 33
  const val minSdk = 26
  const val versionCode = 1
  const val versionName = "1.0.0"
  const val kotlin = "1.4.32"
  const val coreKtx = "1.9.0"
  const val appCompat = "1.6.1"
  const val material = "1.8.0"
  const val dagger = "2.34.1"
  const val junit = "4.13.2"
  const val testExtJunit = "1.1.5"
  const val espressoCore = "3.5.1"
  const val jvmTarget = "11"
  const val hiltAndroid = "2.44.2"
  const val hiltCompose = "1.0.0"
  const val gradlePlugin = "7.3.1"
  const val kotlinPlugin = "1.8.0"
  const val hamcrest = "2.2"
  const val robolectric = "4.9"
  const val mockito = "4.1.0"
  const val androidTestCore = "1.5.0"
  const val junitKotlin = "1.1.5"
  const val archCoreTest = "2.2.0"
  const val splashscreen = "1.0.0"
  const val coroutines = "1.6.1"
  const val lifecycleRuntime = "2.4.1"
  const val activityKtx = "1.4.0"
  const val timber = "5.0.1"
  const val androidPaging = "3.1.1"
  const val datastorePref = "1.0.0"
  const val mockk = "1.12.3"
  const val coroutinesTest = "1.6.4"
  const val testTruth = "1.3.0"
  const val compose = "1.3.3"
  const val materialIcons = "1.3.1"
  const val foundation = "1.3.1"
  const val material3 = "1.0.1"
  const val fragmentTesting = "1.5.5"
  const val fragmentKtx = "1.5.5"
  const val testTurbine = "0.7.0"
  const val activityCompose = "1.4.0"
  const val viewModelCompose = "2.6.0"
  const val constraintCompose = "1.0.1"
  const val lottieCompose = "5.0.3"
  const val pagingCompose =  "1.0.0-alpha18"
  const val coil =  "2.0.0-rc02"
  const val swipe =  "0.28.0"
  const val systemController =  "0.23.1"
  const val webview = "0.24.4-alpha"
  const val datastore = "1.0.0"
  const val moshi = "1.13.0"
  const val securityPref = "1.1.0-alpha05"
  const val navigationCompose = "2.5.3"
  const val destination = "1.8.36-beta"
  const val savedState = "1.2.0"
  const val kotlinSymbolProcessing = "1.8.0-1.0.9"
  const val room = "2.5.0"
  const val moshiCodegen = "1.13.0"
  const val moshiLazyAdapter = "2.2"
  const val retrofit = "2.9.0"
  const val retrofitMoshi = "2.9.0"
  const val okhttp = "5.0.0-alpha.6"
  const val loggingInterceptor = "5.0.0-alpha.6"
  const val chuckerDebug = "3.5.2"
  const val chuckerRelease = "3.5.2"
}
